/* ItemType + RoleTypeId from Assembly-CSharp.dll (SCP: Secret Laboratory). */
window.CC_DATA = {
  maxHealth: 65535,
  inventorySlots: 8,
  commandName: "cc",
  commandAlias: "createcharacter",

  infoMask: [
    { bit: 1, key: "Nickname", label: "Никнейм", hint: "Отображаемое имя над игроком" },
    { bit: 2, key: "Badge", label: "Бейдж", hint: "Цветная подпись сервера над ником" },
    { bit: 4, key: "CustomInfo", label: "Кастом-инфо", hint: "Текст над ником" },
    { bit: 8, key: "Role", label: "Информация об игроке", hint: "Роль под ником (Класс D, МОГ…)" },
    { bit: 16, key: "UnitName", label: "Отряд", hint: "Номер юнита МОГ / ПХ" },
    { bit: 32, key: "PowerStatus", label: "Питание", hint: "Только SCP-079" },
  ],

  ammo: [
    { id: "Nato9", aliases: ["Ammo9x19", "9", "9x19"], label: "9×19 мм", sub: "Nato9", item: "Ammo9x19" },
    { id: "Nato556", aliases: ["Ammo556x45", "556", "5.56"], label: "5.56×45 мм", sub: "Nato556", item: "Ammo556x45" },
    { id: "Nato762", aliases: ["Ammo762x39", "762", "7.62"], label: "7.62×39 мм", sub: "Nato762", item: "Ammo762x39" },
    { id: "Ammo12Gauge", aliases: ["Ammo12gauge", "12"], label: "12 калибр", sub: "Ammo12Gauge", item: "Ammo12gauge" },
    { id: "Ammo44Cal", aliases: ["Ammo44cal", "44"], label: ".44 калибр", sub: "Ammo44Cal", item: "Ammo44cal" },
  ],

  roleFactions: [
    { id: "keep", label: "Не менять" },
    { id: "dclass", label: "Класс D" },
    { id: "science", label: "Научные Сотрудники" },
    { id: "guard", label: "Охрана комплекса" },
    { id: "mtf", label: "МОГ" },
    { id: "chaos", label: "Повстанцы Хаоса" },
    { id: "scp", label: "SCP Объекты" },
    { id: "other", label: "Прочее" },
  ],

  roles: [
    { id: "None", name: "Отсутствует", faction: "none", color: "#6b7787", search: "none пусто -" },
    { id: "ClassD", name: "Персонал Класса D", faction: "dclass", color: "#e8944a", search: "classd d-class класс д заключённый" },
    { id: "Scientist", name: "Научный Сотрудник", faction: "science", color: "#e6d56a", search: "scientist учёный научный" },
    { id: "FacilityGuard", name: "Охранник Комплекса", faction: "guard", color: "#8a9aab", search: "facilityguard guard охрана" },
    { id: "NtfPrivate", name: "Девятихвостая Лиса — Рядовой", faction: "mtf", color: "#6ea0ff", search: "ntfprivate mtf рядовой мог дл nine tailed fox" },
    { id: "NtfSergeant", name: "Девятихвостая Лиса — Сержант", faction: "mtf", color: "#4a78e8", search: "ntfsergeant mtf сержант мог дл" },
    { id: "NtfSpecialist", name: "Девятихвостая Лиса — Специалист", faction: "mtf", color: "#5b8cff", search: "ntfspecialist mtf специалист мог дл" },
    { id: "NtfCaptain", name: "Девятихвостая Лиса — Капитан", faction: "mtf", color: "#3d63d8", search: "ntfcaptain mtf капитан мог дл commander" },
    { id: "ChaosConscript", name: "Повстанец Хаоса — Новобранец", faction: "chaos", color: "#4caf6a", search: "chaosconscript ci новобранец призывник пх" },
    { id: "ChaosRifleman", name: "Повстанец Хаоса — Стрелок", faction: "chaos", color: "#3d9a58", search: "chaosrifleman ci стрелок пх" },
    { id: "ChaosMarauder", name: "Повстанец Хаоса — Мародёр", faction: "chaos", color: "#2e7d46", search: "chaosmarauder ci мародёр пх" },
    { id: "ChaosRepressor", name: "Повстанец Хаоса — Усмиритель", faction: "chaos", color: "#24663a", search: "chaosrepressor ci усмиритель пх" },
    { id: "Scp049", name: "SCP-049", faction: "scp", color: "#6b8f71", search: "scp049 чумной доктор plague" },
    { id: "Scp0492", name: "SCP-049-2", faction: "scp", color: "#6b8f71", search: "scp0492 излеченный зомби zombie" },
    { id: "Scp079", name: "SCP-079", faction: "scp", color: "#4aa3d9", search: "scp079 старый ии компьютер" },
    { id: "Scp096", name: "SCP-096", faction: "scp", color: "#c9d2dc", search: "scp096 скромник shy guy" },
    { id: "Scp106", name: "SCP-106", faction: "scp", color: "#5a4a6a", search: "scp106 старик larry" },
    { id: "Scp173", name: "SCP-173", faction: "scp", color: "#d14b4b", search: "scp173 скульптура орех peanut" },
    { id: "Scp939", name: "SCP-939", faction: "scp", color: "#c45c5c", search: "scp939 со множеством голосов собака" },
    { id: "Scp3114", name: "SCP-3114", faction: "scp", color: "#e0d7c8", search: "scp3114 скелет чувствуешь прохладу" },
    { id: "Tutorial", name: "Обучение", faction: "other", color: "#b07ad8", search: "tutorial обучение" },
    { id: "Flamingo", name: "SCP-1507", faction: "other", color: "#f0a0b8", search: "flamingo фламинго 1507 розовые" },
    { id: "AlphaFlamingo", name: "SCP-1507-Альфа", faction: "other", color: "#e8789a", search: "alphaflamingo альфа фламинго 1507 розовые" },
    { id: "ZombieFlamingo", name: "SCP-1507-049", faction: "other", color: "#8f6a78", search: "zombieflamingo зомби фламинго 1507" },
    { id: "NtfFlamingo", name: "Девятихвостый Фламинго", faction: "mtf", color: "#7aa0e8", search: "ntfflamingo мог фламинго синие" },
    { id: "ChaosFlamingo", name: "Фламинго Повстанцев Хаоса", faction: "chaos", color: "#7bc48a", search: "chaosflamingo пх фламинго зелёные" },
  ],

  itemCategories: [
    { id: "all", label: "Все" },
    { id: "keycard", label: "Ключ-карты" },
    { id: "firearm", label: "Оружие" },
    { id: "special", label: "Особое оружие" },
    { id: "armor", label: "Броня" },
    { id: "medical", label: "Медицина" },
    { id: "grenade", label: "Гранаты" },
    { id: "scp", label: "SCP-предметы" },
    { id: "tool", label: "Снаряжение" },
    { id: "misc", label: "Прочее" },
  ],

  items: [
    { id: "KeycardJanitor", name: "Ключ-карта Уборщика", category: "keycard", search: "keycardjanitor уборщик janitor" },
    { id: "KeycardScientist", name: "Ключ-карта Научного Сотрудника", category: "keycard", search: "keycardscientist учёный scientist" },
    { id: "KeycardResearchCoordinator", name: "Ключ-карта Научного Руководителя", category: "keycard", search: "keycardresearchcoordinator руководитель supervisor" },
    { id: "KeycardZoneManager", name: "Ключ-карта Менеджера Зон Содержания", category: "keycard", search: "keycardzonemanager менеджер зоны" },
    { id: "KeycardGuard", name: "Ключ-карта Охранника", category: "keycard", search: "keycardguard охранник guard" },
    { id: "KeycardMTFPrivate", name: "Ключ-карта Рядового МОГ", category: "keycard", search: "keycardmtfprivate рядовой cadet мог" },
    { id: "KeycardContainmentEngineer", name: "Ключ-карта Инженера Камер Содержания", category: "keycard", search: "keycardcontainmentengineer инженер containment" },
    { id: "KeycardMTFOperative", name: "Ключ-карта Оперативника МОГ", category: "keycard", search: "keycardmtfoperative оперативник lieutenant мог" },
    { id: "KeycardMTFCaptain", name: "Ключ-карта Капитана МОГ", category: "keycard", search: "keycardmtfcaptain капитан commander мог" },
    { id: "KeycardFacilityManager", name: "Ключ-карта Менеджера Комплекса", category: "keycard", search: "keycardfacilitymanager менеджер комплекса" },
    { id: "KeycardChaosInsurgency", name: "Устройство Доступа Повстанцев Хаоса", category: "keycard", search: "keycardchaosinsurgency хаос ciad" },
    { id: "KeycardO5", name: "Ключ-карта Совета О5", category: "keycard", search: "keycardo5 o5 совет" },
    { id: "SurfaceAccessPass", name: "Пропуск на поверхность", category: "keycard", search: "surfaceaccesspass пропуск поверхность" },
    { id: "GunCOM15", name: "COM-15", category: "firearm", search: "guncom15 пистолет" },
    { id: "GunCOM18", name: "COM-18", category: "firearm", search: "guncom18 пистолет" },
    { id: "GunCom45", name: "COM-45", category: "firearm", search: "guncom45" },
    { id: "GunFSP9", name: "FSP-9", category: "firearm", search: "gunfsp9 smg" },
    { id: "GunCrossvec", name: "Crossvec", category: "firearm", search: "guncrossvec вектор" },
    { id: "GunE11SR", name: "МОГ-E11-SR", category: "firearm", search: "gune11sr e11 винтовка мог mtf" },
    { id: "GunFRMG0", name: "FR-MG-0", category: "firearm", search: "gunfrmg0 пулемёт" },
    { id: "GunAK", name: "AK", category: "firearm", search: "gunak ак" },
    { id: "GunA7", name: "A7", category: "firearm", search: "guna7" },
    { id: "GunLogicer", name: "Logicer", category: "firearm", search: "gunlogicer логикер пулемёт" },
    { id: "GunRevolver", name: "Револьвер .44 Калибра", category: "firearm", search: "gunrevolver револьвер" },
    { id: "GunShotgun", name: "Дробовик", category: "firearm", search: "gunshotgun shotgun" },
    { id: "MicroHID", name: "Micro H.I.D.", category: "special", search: "microhid микрохид hid" },
    { id: "ParticleDisruptor", name: "Трёхкратный Молекулярный Разрушитель", category: "special", search: "particledisruptor 3-x лазер разрушитель" },
    { id: "Jailbird", name: "Арестант", category: "special", search: "jailbird арестант дубинка" },
    { id: "GunSCP127", name: "SCP-127", category: "special", search: "gunscp127 органика" },
    { id: "ArmorLight", name: "Лёгкая Броня", category: "armor", search: "armorlight лёгкая" },
    { id: "ArmorCombat", name: "Боевая Броня", category: "armor", search: "armorcombat боевая" },
    { id: "ArmorHeavy", name: "Тяжёлая Броня", category: "armor", search: "armorheavy тяжёлая" },
    { id: "Medkit", name: "Аптечка", category: "medical", search: "medkit аптечка" },
    { id: "Adrenaline", name: "Адреналин", category: "medical", search: "adrenaline шприц" },
    { id: "Painkillers", name: "Обезболивающее", category: "medical", search: "painkillers таблетки" },
    { id: "GrenadeHE", name: "Осколочно-Фугасная Граната", category: "grenade", search: "grenadehe осколочная фугасная frag" },
    { id: "GrenadeFlash", name: "Светошумовая Граната", category: "grenade", search: "grenadeflash флеш flashbang" },
    { id: "SCP500", name: "SCP-500", category: "scp", search: "scp500 панацея pills" },
    { id: "SCP207", name: "SCP-207", category: "scp", search: "scp207 кола soda бутылки кока-кола" },
    { id: "AntiSCP207", name: "Анти-Кола", category: "scp", search: "antiscp207 антикола anti йолок-акок" },
    { id: "SCP018", name: "SCP-018", category: "scp", search: "scp018 супермяч мяч ball super ball" },
    { id: "SCP268", name: "SCP-268", category: "scp", search: "scp268 кепка-невидимка шапка cap" },
    { id: "SCP330", name: "Мешок конфет", category: "scp", search: "scp330 конфеты candy" },
    { id: "SCP2176", name: "SCP-2176", category: "scp", search: "scp2176 призрачный свет лампа ghost light" },
    { id: "SCP244a", name: "SCP-244-A", category: "scp", search: "scp244a ваза кувшин туман" },
    { id: "SCP244b", name: "SCP-244-B", category: "scp", search: "scp244b ваза кувшин туман" },
    { id: "SCP1853", name: "SCP-1853", category: "scp", search: "scp1853" },
    { id: "SCP1576", name: "SCP-1576", category: "scp", search: "scp1576 коммуникатор эдисона загробной жизни" },
    { id: "SCP1344", name: "SCP-1344", category: "scp", search: "scp1344 очки-глазохваты" },
    { id: "SCP1507Tape", name: "Кассетный плеер?", category: "scp", search: "scp1507tape кассета плеер 1507" },
    { id: "SCP1509", name: "SCP-1509", category: "scp", search: "scp1509 клинок перерождения" },
    { id: "Scp021J", name: "SCP-021-J", category: "scp", search: "scp021j злая бутылка" },
    { id: "Radio", name: "Рация", category: "tool", search: "radio рация" },
    { id: "Flashlight", name: "Фонарик", category: "tool", search: "flashlight фонарик свет" },
    { id: "Lantern", name: "Лампа", category: "tool", search: "lantern лампа даниэль" },
    { id: "Coin", name: "Монета", category: "tool", search: "coin монета" },
    { id: "Snowball", name: "Снежок", category: "misc", search: "snowball снежок" },
    { id: "Coal", name: "Уголь", category: "misc", search: "coal уголь" },
    { id: "SpecialCoal", name: "Уголь?", category: "misc", search: "specialcoal уголь" },
    { id: "MarshmallowItem", name: "Зефир", category: "misc", search: "marshmallowitem зефир marshmallow" },
    { id: "DebugRagdollMover", name: "Debug Ragdoll Mover", category: "misc", search: "debugragdollmover debug" },
  ],

  namedColors: [
    "#ffffff", "#c0c0c0", "#888888", "#ff4d4d", "#ff8a3d", "#ffd166",
    "#50C878", "#3dd6c6", "#5b8cff", "#7c5cff", "#f06292", "#00bcd4",
    "#a5d6a7", "#ce93d8", "#ffe082", "#90caf9",
  ],

  armorRoles: [
    "ClassD", "Scientist", "FacilityGuard", "Tutorial",
    "NtfPrivate", "NtfSergeant", "NtfSpecialist", "NtfCaptain",
    "ChaosConscript", "ChaosRifleman", "ChaosMarauder", "ChaosRepressor",
  ],

  /* Used only if templates/*.json cannot be fetched (file://). */
  customItems: [
    { source: "exiled", value: "700", name: "ПНВ" },
    { source: "capi", value: "Taser", name: "Taser" },
    { source: "capi", value: "Cuffs049", name: "Cuffs049" },
    { source: "capi", value: "Cage173", name: "Cage173" },
    { source: "capi", value: "Bag096", name: "Bag096" },
    { source: "capi", value: "Tranq", name: "Tranq" },
    { source: "capi", value: "GuardBaton", name: "GuardBaton" },
  ],
  serverTemplates: {
    folders: [
      {
        id: "examples",
        name: "Примеры",
        items: [
          {
            id: "mogovets",
            name: "Моговец",
            payload: {
              role: "NtfSpecialist",
              useNick: true,
              nick: "Foltler",
              useCinfo: true,
              cinfo: "<color=#50C878><size=10><b>Моговец в спецовке</b></size></color>",
              useHp: true,
              hp: 100,
              items: [
                { source: "auto", value: "Coin" },
                { source: "auto", value: "Flashlight" },
              ],
              ammo: { Nato9: 264 },
              mask: 5,
            },
          },
        ],
      },
    ],
  },
};
